services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    ports:
      - "1434:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
